if(NOT DEFINED GMSH_INCLUDE_DIRS)
if(NOT DEFINED DO_NOT_USE_NATIVE_GMSH)
    find_path(GMSH_INCLUDE_DIRS NAMES onelab.h PATH_SUFFIXES gmsh)
    if (GMSH_INCLUDE_DIRS)
        message(STATUS "LibGmsh includes found at ${GMSH_INCLUDE_DIR}.")
    else()
        message(STATUS "LibGmsh includes not found, falling back to redist.")
        set(GMSH_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/thirdparty/gmsh)
    endif()
else()
    set(GMSH_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/thirdparty/gmsh)
endif()
endif()
set(GMSH_FOUND)
